spring:
  application:
    name: amps-publisher
#  docker:
#    compose:
#      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  level:
    root: INFO

amps:
  client-name: publisher-client
  host: 172.21.12.69
  port: 9007
  topic: orders
  queue: orders-queue

publisher:
  queue-capacity: 10000
  batch-size: 100

server:
  port: 4040