spring:
  application:
    name: amps-subscriber


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

logging:
  file:
    name: logs/subscriber.log

  level:
    root: INFO

amps:
  client-name: subscriber-client
  host: localhost
  port: 9007
  topic: orders
  queue: orders-queue

consumer:
  worker-threads: 8
  queue-capacity: 50000